name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and push exporter
      uses: docker/build-push-action@v1.1.0
      with:
        username: lexfrei
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: lexfrei/gow/ow-exporter
        tag_with_ref: true
        tag_with_sha: true
        registry: docker.pkg.github.com
        dockerfile: build/exporter/Dockerfile

    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: lexfrei/gow/ow-exporter
