name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: lexfrei
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: docker.pkg.github.com/lexfrei/gow/ow-exporter
        tag_with_ref: true
        registry: docker.pkg.github.com
