name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and push exporter
      uses: docker/build-push-action@v1.1.0
      with:
        username: lexfrei
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: lexfrei/gow/ow-exporter
        tag_with_ref: true
        tag_with_sha: true
        registry: docker.pkg.github.com
        dockerfile: cmd/exporter/Dockerfile
